

import java.awt.*;
import java.awt.event.KeyEvent;

import java.sql.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


import static javax.management.Query.and;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class adminnewupdatetravel extends javax.swing.JFrame {

    /**
     * Creates new form Travel
     */
    public adminnewupdatetravel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TravelTo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Kilometers = new javax.swing.JTextField();
        TravelFrom = new javax.swing.JTextField();
        BagsCarried = new javax.swing.JTextField();
        PriceBag = new javax.swing.JTextField();
        TotalPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ctrl = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Date = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        PlateBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Travel from");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Travel to");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Price per bag");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Bags carried");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TravelTo.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        TravelTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TravelToActionPerformed(evt);
            }
        });
        jPanel1.add(TravelTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 154, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Kilometers");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        Kilometers.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jPanel1.add(Kilometers, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 154, -1));

        TravelFrom.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jPanel1.add(TravelFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 154, -1));

        BagsCarried.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jPanel1.add(BagsCarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 154, -1));

        PriceBag.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jPanel1.add(PriceBag, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 154, -1));

        TotalPrice.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jPanel1.add(TotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 154, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Control Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        ctrl.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        ctrl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlActionPerformed(evt);
            }
        });
        jPanel1.add(ctrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, -1));

        jButton2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton2.setText("INSERT");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, 100, -1));

        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton3.setText("Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 100, -1));

        Date.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 154, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Plate Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        PlateBox.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        PlateBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        PlateBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlateBoxActionPerformed(evt);
            }
        });
        jPanel1.add(PlateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 154, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genbg1.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new adminmenu().setVisible(true);
        this.dispose();  
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String dates = Date.getText();
        String control = ctrl.getText();
        String plate = PlateBox.getSelectedItem().toString();
        String tto = TravelTo.getText();
        String tfrom = TravelFrom.getText();
        int km = Integer.parseInt(Kilometers.getText());
        int bcarried = Integer.parseInt(BagsCarried.getText());
        int bprice = Integer.parseInt(PriceBag.getText());
        int tprice = Integer.parseInt(TotalPrice.getText());
        
        try{
         Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/billing","root","");
        PreparedStatement pst = (PreparedStatement) con.prepareStatement("INSERT INTO traveldet(date,CtrlNo, PlateNo, Travelto, Travelfrom, Km, PiecesBag, PriceBag, ShippingTotal )Values(?,?,?,?,?,?,?,?,?)"); 
        
            pst.setString(1,dates);
            pst.setString(2,control);
            pst.setString(3,plate);
            pst.setString(4,tto);   
            pst.setString(5,tfrom);
            pst.setInt(6,km);
            pst.setInt(7,bcarried);
            pst.setInt(8,bprice);
            pst.setInt(9,tprice);
            
            int k = pst.executeUpdate();
            
            if(k==1){
             Date.setText("");  
             ctrl.setText("");
             TravelTo.setText("");
             TravelFrom.setText("");
             Kilometers.setText("");
             BagsCarried.setText("");
             PriceBag.setText("");
             TravelFrom.setText("");
             TotalPrice.setText("");
             
             JOptionPane.showMessageDialog(null, "Travel Details added");
            }
        
        }catch(SQLException ex) {
          Logger.getLogger(adminnewupdatetravel.class.getName()).log(Level.SEVERE, null, ex);  
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int km = Integer.parseInt(Kilometers.getText());
        int bcarried = Integer.parseInt(BagsCarried.getText());
        int bprice = Integer.parseInt(PriceBag.getText());
        
 
        
        if(km>1){
               if(km<=20){
                   int kmp = 1500;
                   int total = bprice*bcarried+kmp;
                   TotalPrice.setText(String.valueOf(total));
                  
               }else{
                   int kmp = (1500+(km-20)*30);
                   int total = bprice*bcarried+kmp;       
                   TotalPrice.setText(String.valueOf(total));
               } 
            }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void PlateBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlateBoxActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "");
            PreparedStatement state = (PreparedStatement) con.prepareStatement("SELECT PlateNumber from truckdet ");
            ResultSet rs = state.executeQuery();

            while (rs.next()) {

                String pnumber = rs.getString("PlateNumber");
                PlateBox.addItem(pnumber);
            }
        } catch (SQLException ex) {
            Logger.getLogger(adminnewupdatetravel.class.getName()).log(Level.SEVERE, null, ex);  
        
        
        }
    }//GEN-LAST:event_PlateBoxActionPerformed

    private void ctrlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ctrlActionPerformed

    private void TravelToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TravelToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TravelToActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminnewupdatetravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminnewupdatetravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminnewupdatetravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminnewupdatetravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminnewupdatetravel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BagsCarried;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Kilometers;
    private javax.swing.JComboBox<String> PlateBox;
    private javax.swing.JTextField PriceBag;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JTextField TravelFrom;
    private javax.swing.JTextField TravelTo;
    private javax.swing.JTextField ctrl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
