
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author user
 */
public class adminmenu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public adminmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        uplog = new javax.swing.JButton();
        dellog = new javax.swing.JButton();
        uptrav = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        newlog = new javax.swing.JButton();
        newtrav = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        bil = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NEW LOGISTICS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("UPDATE/VIEW ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("DELETE LOGISTICS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("NEW TRAVEL");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("SEARCH/UPDATE ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("DELETE TRAVEL");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        uplog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled.png"))); // NOI18N
        uplog.setMaximumSize(new java.awt.Dimension(119, 60));
        uplog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uplogActionPerformed(evt);
            }
        });
        jPanel1.add(uplog, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 120, 70));

        dellog.setForeground(new java.awt.Color(204, 204, 204));
        dellog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/deltruck.png"))); // NOI18N
        dellog.setMaximumSize(new java.awt.Dimension(119, 60));
        dellog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dellogActionPerformed(evt);
            }
        });
        jPanel1.add(dellog, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 120, 70));

        uptrav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uptrav.png"))); // NOI18N
        uptrav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uptravActionPerformed(evt);
            }
        });
        jPanel1.add(uptrav, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 120, 70));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("LIGHTNING CORP.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        newlog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addlog.png"))); // NOI18N
        newlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newlogActionPerformed(evt);
            }
        });
        jPanel1.add(newlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, 70));

        newtrav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addtrav.png"))); // NOI18N
        newtrav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newtravActionPerformed(evt);
            }
        });
        jPanel1.add(newtrav, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 120, 70));

        logout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logbut (1).png"))); // NOI18N
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, 30));

        bil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bill.png"))); // NOI18N
        bil.setText("BILL");
        bil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilActionPerformed(evt);
            }
        });
        jPanel1.add(bil, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, 50));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        jButton1.setText("ADD USER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flash-wallpaper-mobile-Is-Cool-768x432 (2).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uplogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uplogActionPerformed
        this.dispose();
        new adminupdate_logistics().setVisible(true);
    }//GEN-LAST:event_uplogActionPerformed

    private void newlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newlogActionPerformed
        this.dispose();
        new adminLogistics().setVisible(true);
    }//GEN-LAST:event_newlogActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.dispose();
        new adminlogin().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    private void newtravActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newtravActionPerformed
        this.dispose();
        new adminnewupdatetravel().setVisible(true);
    }//GEN-LAST:event_newtravActionPerformed

    private void uptravActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uptravActionPerformed
        this.dispose();
        new adminupdatetravel().setVisible(true);
    }//GEN-LAST:event_uptravActionPerformed

    private void dellogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dellogActionPerformed
        this.dispose();
        new admindeletelogistics().setVisible(true);
    }//GEN-LAST:event_dellogActionPerformed

    private void bilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilActionPerformed
        this.dispose();
       new adminviewtravel().setVisible(true);
    }//GEN-LAST:event_bilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        new newuser().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bil;
    private javax.swing.JButton dellog;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logout;
    private javax.swing.JButton newlog;
    private javax.swing.JButton newtrav;
    private javax.swing.JButton uplog;
    private javax.swing.JButton uptrav;
    // End of variables declaration//GEN-END:variables
}
