import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

public class newuser extends javax.swing.JFrame {


    public newuser() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Un = new java.awt.TextField();
        jLabel2 = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        admincreate = new javax.swing.JButton();
        staffcreate = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 104, 28));
        getContentPane().add(Un, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 250, 28));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 104, 28));
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 250, 28));

        admincreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        admincreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        admincreate.setText("ADMIN");
        admincreate.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        admincreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admincreateActionPerformed(evt);
            }
        });
        getContentPane().add(admincreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 90, 20));

        staffcreate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        staffcreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login.png"))); // NOI18N
        staffcreate.setText("STAFF");
        staffcreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffcreateActionPerformed(evt);
            }
        });
        getContentPane().add(staffcreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 100, 20));

        back.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back.setText("BACK");
        back.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 90, 20));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 26)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CREATE NEW USER");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 200, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genbg1.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admincreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admincreateActionPerformed
        String Uname = Un.getText();
        String Password = pass.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            // establish connection
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "");
            Statement statement = con.createStatement();

            statement.executeUpdate(
                    String.format("INSERT adminlogin VALUES('%s','%s')",
                           Un.getText(),pass.getText() ));
            JOptionPane.showMessageDialog(null, "Record added successfully!");
            statement.close();
            con.close();
            Clear();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_admincreateActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        new adminmenu().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void staffcreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffcreateActionPerformed
        String Uname = Un.getText();
        String Password = pass.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver");
            // establish connection
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "");
            Statement statement = con.createStatement();

            statement.executeUpdate(
                    String.format("INSERT stafflogin VALUES('%s','%s')",
                           Un.getText(),pass.getText() ));
            JOptionPane.showMessageDialog(null, "Record added successfully!");
            statement.close();
            con.close();
            Clear();
        } catch (SQLException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_staffcreateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newuser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newuser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Un;
    private javax.swing.JButton admincreate;
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton staffcreate;
    // End of variables declaration//GEN-END:variables

    private void Clear() {
       Un.setText("");
       pass.setText("");
              
    }
}
