

import java.awt.*;
import java.awt.event.KeyEvent;

import java.sql.*;
import javax.swing.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;


import static javax.management.Query.and;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class staffupdatetravel extends javax.swing.JFrame {

    /**
     * Creates new form Travel
     */
    public staffupdatetravel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CTRLBOX = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Pnumber = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        TravelTo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Kilometers = new javax.swing.JTextField();
        TravelFrom = new javax.swing.JTextField();
        BagsCarried = new javax.swing.JTextField();
        PriceBag = new javax.swing.JTextField();
        TotalPrice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        SEARCH = new javax.swing.JButton();
        Date = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 153));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CTRLBOX.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 16)); // NOI18N
        CTRLBOX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        CTRLBOX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CTRLBOXActionPerformed(evt);
            }
        });
        jPanel1.add(CTRLBOX, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 150, -1));

        jButton5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 100, -1));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("Travel from");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Travel to");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Price per bag");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, -1));

        Pnumber.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        Pnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PnumberActionPerformed(evt);
            }
        });
        jPanel1.add(Pnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 154, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Bags carried");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, -1, -1));

        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TravelTo.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jPanel1.add(TravelTo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 154, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Total");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, -1, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Kilometers");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        Kilometers.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jPanel1.add(Kilometers, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 154, -1));

        TravelFrom.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jPanel1.add(TravelFrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 154, -1));

        BagsCarried.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jPanel1.add(BagsCarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 154, -1));

        PriceBag.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        jPanel1.add(PriceBag, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 154, -1));

        TotalPrice.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        TotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalPriceActionPerformed(evt);
            }
        });
        jPanel1.add(TotalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 154, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Control Number");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jButton3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jButton3.setText("Total");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 200, 100, -1));

        SEARCH.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        SEARCH.setText("Search");
        SEARCH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHActionPerformed(evt);
            }
        });
        jPanel1.add(SEARCH, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        Date.setFont(new java.awt.Font("Tw Cen MT", 0, 16)); // NOI18N
        Date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateActionPerformed(evt);
            }
        });
        jPanel1.add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, 154, -1));

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Plate Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/genbg1.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new staffmenu().setVisible(true);
        this.dispose();  
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int km = Integer.parseInt(Kilometers.getText());
        int bcarried = Integer.parseInt(BagsCarried.getText());
        int bprice = Integer.parseInt(PriceBag.getText());
        
 
        
        if(km>1){
               if(km<=20){
                   int kmp = 1500;
                   int total = bprice*bcarried+kmp;
                   TotalPrice.setText(String.valueOf(total));
                  
               }else{
                   int kmp = (1500+(km-20)*30);
                   int total = bprice*bcarried+kmp;       
                   TotalPrice.setText(String.valueOf(total));
               } 
            }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void DateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateActionPerformed

    private void SEARCHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHActionPerformed
        // TODO add your handling code here:
        try {

            String control= CTRLBOX.getSelectedItem().toString();
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "");
            PreparedStatement state = con.prepareStatement("select * from traveldet where CtrlNo = ?");
            state.setString(1, control);
            ResultSet s = state.executeQuery();

            if (s.next()) {
                String r =  s.getString(1);
                String r1 = s.getString(2);
                String r2 = s.getString(3);
                String r3 = s.getString(4);
                String r4 = s.getString(5);
                String r5 = s.getString(6);
                String r6 = s.getString(7);
                String r7 = s.getString(8);
                String r8 = s.getString(9);

                Date.setText(r);
 
                Pnumber.setText(r2);
                TravelTo.setText(r3);
                TravelFrom.setText(r4);
                Kilometers.setText(r5);
                BagsCarried.setText(r6);
                PriceBag.setText(r7);
                TotalPrice.setText(r8);

            } else {
                JOptionPane.showMessageDialog(null, "No Records Found");

                // establish connection
            }
        } catch (SQLException sqlException) {
            JOptionPane.showMessageDialog(null, sqlException);
        }
    }//GEN-LAST:event_SEARCHActionPerformed

    private void CTRLBOXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CTRLBOXActionPerformed
            try {
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "");
            PreparedStatement state = (PreparedStatement) con.prepareStatement("SELECT CtrlNo from traveldet ");
            ResultSet rs = state.executeQuery();

            while (rs.next()) {

                String control = rs.getString("CtrlNo");
                CTRLBOX.addItem(control);
            }
        } catch (SQLException ex) {
            Logger.getLogger(adminnewupdatetravel.class.getName()).log(Level.SEVERE, null, ex);  
        
        
        }
    }//GEN-LAST:event_CTRLBOXActionPerformed

    private void PnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PnumberActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        try {
            String dates = Date.getText();
            String control = CTRLBOX.getSelectedItem().toString();
            String plate = Pnumber.getText();
            String tto = TravelTo.getText();
            String tfrom = TravelFrom.getText();
            int km = Integer.parseInt(Kilometers.getText());
            int bcarried = Integer.parseInt(BagsCarried.getText());
            int bprice = Integer.parseInt(PriceBag.getText());
            int tprice = Integer.parseInt(TotalPrice.getText());
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/billing", "root", "");

            int a = JOptionPane.showConfirmDialog(null, "Are you sure you want to save the changes?");

            if (a == JOptionPane.YES_OPTION) {

                PreparedStatement pst = (PreparedStatement) con.prepareStatement("Update traveldet set date = ? , CtrlNo=? , PlateNo=?, Travelto=?, Travelfrom=?, Km=?, PiecesBag=?, PriceBag=?, ShippingTotal=? where CtrlNo= ? ");

                pst.setString(1,dates);
                pst.setString(2,control);
                pst.setString(3,plate);
                pst.setString(4,tto);
                pst.setString(5,tfrom);
                pst.setInt(6,km);
                pst.setInt(7,bcarried);
                pst.setInt(8,bprice);
                pst.setInt(9,tprice);
                pst.setString(10,control);

                pst.executeUpdate();

                JOptionPane.showMessageDialog(null, "Record is updated!");

                pst.close();

                con.close();

            } else {

                JOptionPane.showMessageDialog(null, "Update cancelled by the user!");

            }

        } catch (SQLException slqException) {

            JOptionPane.showMessageDialog(null, slqException);

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void TotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalPriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminnewupdatetravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminnewupdatetravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminnewupdatetravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminnewupdatetravel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffnewupdatetravel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BagsCarried;
    private javax.swing.JComboBox<String> CTRLBOX;
    private javax.swing.JTextField Date;
    private javax.swing.JTextField Kilometers;
    private javax.swing.JTextField Pnumber;
    private javax.swing.JTextField PriceBag;
    private javax.swing.JButton SEARCH;
    private javax.swing.JTextField TotalPrice;
    private javax.swing.JTextField TravelFrom;
    private javax.swing.JTextField TravelTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
