
public class staffmenu extends javax.swing.JFrame {

    /**
     * Creates new form staffmenu
     */
    public staffmenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        newlog = new javax.swing.JButton();
        uplog = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        newtrav = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        uptrav = new javax.swing.JButton();
        bil = new javax.swing.JButton();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("LIGHTNING CORP.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        newlog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addlog.png"))); // NOI18N
        newlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newlogActionPerformed(evt);
            }
        });
        getContentPane().add(newlog, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 120, 70));

        uplog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled.png"))); // NOI18N
        uplog.setMaximumSize(new java.awt.Dimension(119, 60));
        uplog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uplogActionPerformed(evt);
            }
        });
        getContentPane().add(uplog, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 120, 70));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("UPDATE/VIEW ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("NEW LOGISTICS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        newtrav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/addtrav.png"))); // NOI18N
        newtrav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newtravActionPerformed(evt);
            }
        });
        getContentPane().add(newtrav, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 120, 70));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("NEW TRAVEL");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("SEARCH/UPDATE ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 270, -1, -1));

        uptrav.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uptrav.png"))); // NOI18N
        uptrav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uptravActionPerformed(evt);
            }
        });
        getContentPane().add(uptrav, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 120, 70));

        bil.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bill.png"))); // NOI18N
        bil.setText("BILL");
        bil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilActionPerformed(evt);
            }
        });
        getContentPane().add(bil, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, -1, 50));

        logout.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logbut (1).png"))); // NOI18N
        logout.setText("LOG OUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Flash-wallpaper-mobile-Is-Cool-768x432 (2).jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newlogActionPerformed
        this.dispose();
        new adminLogistics().setVisible(true);
    }//GEN-LAST:event_newlogActionPerformed

    private void uplogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uplogActionPerformed
        this.dispose();
        new adminupdate_logistics().setVisible(true);
    }//GEN-LAST:event_uplogActionPerformed

    private void newtravActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newtravActionPerformed
        this.dispose();
        new adminnewupdatetravel().setVisible(true);
    }//GEN-LAST:event_newtravActionPerformed

    private void uptravActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uptravActionPerformed
        this.dispose();
        new adminupdatetravel().setVisible(true);
    }//GEN-LAST:event_uptravActionPerformed

    private void bilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilActionPerformed
        this.dispose();
        new adminviewtravel().setVisible(true);
    }//GEN-LAST:event_bilActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        this.dispose();
        new adminlogin().setVisible(true);
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(staffmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(staffmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(staffmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(staffmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new staffmenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton logout;
    private javax.swing.JButton newlog;
    private javax.swing.JButton newtrav;
    private javax.swing.JButton uplog;
    private javax.swing.JButton uptrav;
    // End of variables declaration//GEN-END:variables
}
